# Gitlab CI config - Courtesy of T. Janvier
default: # linux image on linux runnner
  image: nexus-docker.brgm.fr/brgm/miniconda3:latest
  tags:
    - brgm

.windows: # windows image on windows runnner
  image: nexus-docker.brgm.fr/brgm/miniconda3:windows
  tags:
    - windows-2022-docker

before_script:
  - echo "gridmarthe ci/cd pipeline"
  - python --version
  - gfortran --version

stages:
  - build
  - test
  - deploy


# .version_tag: &version_tag
  # only:
    # variables: # see https://peps.python.org/pep-0440/
      # - $CI_COMMIT_TAG =~ /^(?P<epoch>\D+)?(?P<version>(?P<release>\d+(?:\.\d+)*)(?P<pre>(?:a|b|rc)\d+?)?((?P<post>\.post\d+))?(?P<dev>\.dev\d+)?(?P<build>\+\S+)?)$/

.only-pepver:
  only: # see https://peps.python.org/pep-0440/
    variables:
      - $CI_COMMIT_TAG =~ /^(?P<epoch>\D+)?(?P<version>(?P<release>\d+(?:\.\d+)*)(?P<pre>(?:a|b|rc)\d+?)?((?P<post>\.post\d+))?(?P<dev>\.dev\d+)?(?P<build>\+\S+)?)$/
  except:
    - branches


# ----- Build ----- #

.build:
  # <<: *version_tag
  stage: build
  extends: .only-pepver
  when: manual
  before_script:
    - python -m pip install cibuildwheel
    # uncomment next line if you need internal dependencies
    # - python -m pip config set global.index-url ${REGISTRY_NEXUS}/pypi-all/simple
  script:
    # build multiple versions using cibuildwheel
    - python -m cibuildwheel --output-dir ./dist 
    # build standalone environment for testing (current package + all dependencies)
    # - python -m pip wheel -w ./dist/wheelhouse .[test]
    - python -m pip wheel -w ./dist/wheelhouse .
  artifacts:
    paths:
    - dist/
    expose_as: wheel
    expire_in: 2 hours
    

build-linux:
  when: manual
  extends: .build

build-windows:
  when: manual
  extends: 
    - .windows
    - .build


# ----- Test config ----- #

.test:
  stage: test
  extends: .only-pepver
  allow_failure: true
  before_script:
    - python -m pip install dist/wheelhouse/*.whl # --no-index --no-deps
  script:
    - python -c 'import gridmarthe'

test-linux:
  extends: .test

test-windows:
  extends: 
    - .windows
    - .test


.deploy:
  extends: .only-pepver
  stage: deploy
  except:
    - branches
  needs: ["build"]


# ----- Publish ----- #

deploy-nexus_snapshot:
  <<: *version_tag
  extends: .deploy
  before_script:
    - echo $REGISTRY_NEXUS_USER
    - echo $REGISTRY_NEXUS
    - pip install twine
  script:
    - twine upload -u ${REGISTRY_NEXUS_USER} -p ${REGISTRY_NEXUS_PASSWORD} --repository-url ${REGISTRY_NEXUS}/pypi-snapshots/ dist/*.whl # dist/wheelhouse/*.whl
  when:
    - manual


deploy-pip:
  <<: *version_tag
  extends: .deploy
  before_script:
    - pip install twine
  script:
    - twine upload dist/*.whl
  when:
    - manual

