# pip install pre-commit
# pre-commit install [--install-hooks] # install git hooks
# pre-commit run [--all-files]  # apply hooks
# files: \.(py|sh|rst|md|toml)$
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
        files: ^src/.*\.py$
      - id: end-of-file-fixer
        files: ^src/.*\.py$
      - id: mixed-line-ending
        args: ['--fix=lf']
        files: ^src/.*\.py$
        exclude: '.*\.bat'   # future, if applied to other files than *.py
        description: Forces to replace line ending by the UNIX 'lf' character.
      - id: check-added-large-files
        args: ['--maxkb=10000']  # Sets the limit to 10MB
      - id: check-yaml
      - id: check-toml
      # - id: check-case-conflict
  - repo: local
    hooks:
      - id: check-uncommitted-test-data
        name: Check uncommitted test data
        entry: tools/hooks/check_uncommitted_test_data.sh
        language: script
        files: ^tests/  # Optional: only run when test files change
  # future:
  # - repo: https://github.com/numpy/numpydoc
  #   rev: v1.11.0
  #   hooks:
  #     - id: numpydoc-validation
  #       log_file: numpydoc-lint.log
  # - repo: https://github.com/astral-sh/ruff-pre-commit
  #   # Ruff version.
  #   rev: v0.15.20
  #   hooks:
  #     # Run the linter.
  #     - id: ruff-check
  #       log_file: ruff-check.log
  #     # Run the formatter // edit, no, use yapf for a softer formatter
  #     # - id: ruff-format
  # - repo: https://github.com/google/yapf
  #   rev: v0.43.0
  #   hooks:
  #     - id: yapf-diff
  #       log_file: yapf-diff.patch
