# mamba env create -n gm -f environment.yml
channels:
  - conda-forge
dependencies:
  # - python=3.12  # deactivate for ci on git repo, you may choose a version here
  # build deps
  - pip
  - uutils-coreutils  # rust cross-platform version of gnu coreutils
  - conda-build
  - make
  - gfortran
  - gcc
  - ninja
  - meson
  - meson-python
  - charset-normalizer
  - numpy
  # gridmarthe deps
  - netcdf4
  - h5netcdf
  - xarray
  - pandas
  - geopandas
  - shapely
  - matplotlib
  - scipy
  - typing_extensions
  - pip:
    - vtkwriters
