# usage: mamba env create -n gm -f environment.yml
# on Windows. This needs an installation of Visual Sutdio
channels:
  - conda-forge
dependencies:
  - python=3.14
  # build deps
  - pip
  - uutils-coreutils  # rust cross-platform version of gnu coreutils
  - make
  - conda-build
  - clang=21
  - flang=21
  - flang-rt_win-64=21
  - lld=21
  - clang-tools
  - meson
  - meson-python
  - ninja
  - charset-normalizer
  - numpy
  # gridmarthe deps
  - netcdf4
  - h5netcdf
  - xarray
  - pandas
  - geopandas
  - shapely
  - matplotlib
  - scipy
  - typing_extensions
  - pip:
    - vtkwriters
