# Gather all function sources from subdirectories
all_functions_sources = []

subdir('lecsem')
all_functions_sources += lecsem_sources

subdir('flowdirect')
all_functions_sources += flowdirect_sources

subdir('rivernetwork')
all_functions_sources += rivernet_sources

subdir('dessin')
all_functions_sources += dessin_sources

subdir('utils')
all_functions_sources += utils_sources

# Add modules in this directory
all_functions_sources += files('modgridmarthe.f90')
