name: Build and Publish

on:
  push:
    branches:
      - ci
  pull_request:
  #if: startsWith(github.ref, 'refs/tags/')  # only publish to PyPI on tag pushes

jobs:
  build_wheels:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        include:
          # to access these variables
          - os: [ubuntu-latest, windows-latest, macos-latest]
    env:
      FC: gfortran
      GCC_V: 12 # only for MACOS
      #TZ: UTC+01:00

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      # install compiler for Fortran dep
      - name: Install gfortran (Windows)
        if: runner.os == 'Windows'
        run: choco install mingw -y
      
      - name: Install gfortran (Linux)
        if: runner.os == 'Linux'
        run: sudo apt-get install -y gcc gfortran

      - name: Install gfortran (MacOS)
        if: runner.os == 'macOS'
        run: brew install gcc
        
      - name: Symlink gfortran (macOS)
        if: runner.os == 'macOS'
        run: |
          # make sure gfortran is available
          # https://github.com/actions/runner-images/blob/main/images/macos/macos-15-Readme.md
          # https://github.com/actions/runner-images/issues/3371
          # ln version - new path 'MacOS14'
          sudo ln -fs /opt/homebrew/bin/gfortran-${GCC_V} /usr/local/bin/gfortran
          sudo mkdir -p /usr/local/gfortran
          sudo ln -sf /opt/homebrew/Cellar/gcc@${GCC_V}/*/lib/gcc/${GCC_V} /usr/local/gfortran/lib
     
      # dép de gcc compilées avec macos latest...
      # TODO compiler avec macos12 et tester sur macos14
      - name: Set macOS deployment target
        if: runner.os == 'macOS'
        run: echo "MACOSX_DEPLOYMENT_TARGET=14.0" >> $GITHUB_ENV
     
      # Check gfortran
      - name: Verify gfortran installation
        run: gfortran --version

      # Build wheels
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install cibuildwheel
        run: pip install cibuildwheel
        
      - name: Build wheels with cibuildwheel
        run: cibuildwheel --output-dir dist
      
      - name: Upload distributions
        uses: actions/upload-artifact@v4
        with:
          name: artifact_${{ matrix.os }}
          path: dist/
          overwrite: true
          # if-no-files-found: ignore
          # retention-days: 1



#  pypi-publish:
#    runs-on: ubuntu-latest
#    needs: build_wheels
#    # Dedicated environments with protections for publishing are strongly recommended.
#    # For more information, see: https://docs.github.com/en/actions/deployment/targeting-different-environments/using-environments-for-deployment#deployment-protection-rules
#    environment:
#      name: pypi
#      # OPTIONAL: uncomment and update to include your PyPI project URL in the deployment status:
#      url: https://pypi.org/p/gridmarthe
#      #
#      # ALTERNATIVE: if your GitHub Release name is the PyPI project version string
#      # ALTERNATIVE: exactly, uncomment the following line instead:
#      # url: https://pypi.org/project/YOURPROJECT/${{ github.event.release.name }}
#    permissions:
#      # IMPORTANT: this permission is mandatory for trusted publishing
#      id-token: write
#    steps:
#      - name: Retrieve release distributions
#        uses: actions/download-artifact@v4
#        with:
#          name: release-dists
#          path: dist/

#      - name: Publish release distributions to PyPI
#        uses: pypa/gh-action-pypi-publish@release/v1
##        with:
##          packages-dir: dist/
#  
  
  publish-to-testpypi:
    name: Publish to TestPyPI
    needs:
    - build_wheels
    runs-on: ubuntu-latest

    environment:
      name: testpypi
      url: https://test.pypi.org/p/gridmarthe

    permissions:
      id-token: write
      # IMPORTANT: mandatory for trusted publishing

    steps:
    - name: Download all the dists
      uses: actions/download-artifact@v4
      with:
        path: dist/
    - name: Publish distribution to TestPyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        repository-url: https://test.pypi.org/legacy/

